name: cicd-demo
on:
  push:
    branches:
      - '*'
jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: 'Start build job'
        run: |
          echo "Starting the build job."
      
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: 'Setup go'
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - run: go version